### ISSUE TITLE
database ER diagram

### ISSUE THREAD

**Issue by MickyBe** [SE-projects/mekina-eziga#14]
disigne the database especially the part you are given

**Comment by MickyBe** [comment]
do what u can and comunicate whith others on your work

**Comment by mahitechane** [comment]
just to give you what er diagram is.
An entity relationship diagram (ERD) shows the relationships of entity sets stored in a database. An entity in this context is an object, a component of data. An entity set is a collection of similar entities. These entities can have attributes that define its properties.
